spring.data.mongodb.uri=mongodb://localhost:27017/spring
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Configuration
server.port=8082

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.application.name=station-service

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fadi6895@gmail.com
spring.mail.password=cplt xfbe lfwj bckf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true