spring.application.name=api-gateway
server.port=8090

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Spring Cloud Gateway Routes
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# User Service Route
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**, /api/auth/**

# Station Service Route
spring.cloud.gateway.routes[1].id=station-service
spring.cloud.gateway.routes[1].uri=lb://station-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/stations/**

# Scooter Service Route
spring.cloud.gateway.routes[2].id=scooter-service
spring.cloud.gateway.routes[2].uri=lb://scooter-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/scooters/**

# Reservation Service Route
spring.cloud.gateway.routes[3].id=reservation-service
spring.cloud.gateway.routes[3].uri=lb://reservation-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/reservations/**

# Payment Service Route
spring.cloud.gateway.routes[4].id=payment-service
spring.cloud.gateway.routes[4].uri=lb://payment-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/payments/**

# Rating Service Route
spring.cloud.gateway.routes[5].id=rating-service
spring.cloud.gateway.routes[5].uri=lb://rating-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/ratings/**

# Keycloak Integration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/andah-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8090/realms/andah-realm/protocol/openid-connect/certs

# Actuator endpoints for monitoring
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Config Server Connection
spring.config.import=optional:configserver:http://localhost:8888
