spring.application.name=reservation-service
spring.config.import=optional:configserver:http://localhost:8888
server.port=8087
#data config
spring.datasource.url=jdbc:mysql://localhost:3306/reservationT?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update



eureka.client.service-url.defaultZone= http://localhost:8761/eureka
eureka.client.register-with-eureka=true
# Email configuration (CORRECT SPRING FORMAT)
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.protocol=smtps
spring.mail.username=samargaiche82@gmail.com
spring.mail.password=rqpzlqrfsquomahc
spring.mail.properties.mail.transport.protocol=smtps
spring.mail.properties.mail.smtps.auth=true
spring.mail.properties.mail.smtps.starttls.enable=true
spring.mail.properties.mail.smtps.timeout=8000


app.jwt.secret=andahSecretKey123ForAllServices
app.jwt.expiration=86400000